In [1]:
import numpy as np

In [3]:
a = np.array([1010, 1000, 990])

In [6]:
np.exp(a) / np.sum(np.exp(a)) # 소프트맥스 함수의 계산 - 제대로 계산되지 않는다

C:\Users\KlimSolution1\AppData\Local\Temp\ipykernel_26608\3880535779.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a)) # 소프트맥스 함수의 계산 - 제대로 계산되지 않는다
C:\Users\KlimSolution1\AppData\Local\Temp\ipykernel_26608\3880535779.py:1: RuntimeWarning: invalid value encountered in divide
  np.exp(a) / np.sum(np.exp(a)) # 소프트맥스 함수의 계산 - 제대로 계산되지 않는다


array([nan, nan, nan])

In [7]:
c = np.max(a) # c = 1010 최댓값

In [8]:
a - c

array([  0, -10, -20])

In [9]:
np.exp(a - c) / np.sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])